### ISSUE TITLE
RTI behaviour

### ISSUE THREAD

**Issue by ghost** [elmerucr/MC6809#1]
Hello,

The only reason I saw this is that I am writing a 6809 emulator and I made the same mistake.

RTI has a different behaviour according to the E bit, but which one exactly?

this code (and mine!) looks at the current value of E in the CC register:
https://github.com/elmerucr/MC6809/blob/master/src/mc6809_instructions.cpp#L1239C6-L1239C19

but this is wrong.

This doc page 120: https://colorcomputerarchive.com/repo/Documents/Books/Motorola%206809%20and%20Hitachi%206309%20Programming%20Reference%20(Darren%20Atkinson).pdf

says that:

> The exact behavior of the RTI instruction depends on the state of the E flag in the _stacked_ CC register and the state of the NM bit in the MD register. (for 6309)

So the first thing to do is : PULL CC, THEN have a look at the E flag, THEN continue pulling the rest of the registers.

The 6809PM here seems to confirm (page 107) that the rest of registers is pulled only if the RECOVERED E bit is set:

https://www.eit.hirosaki-u.ac.jp/~ken/CAE/man6809.pdf

Best regards

**Comment by elmerucr** [comment]
Dear Slorquet,

Thanks for your message. I checked my code, and if I’m not mistaken, it follows exactly the defined procedure, it first pulls the cc from the stack, and the e flag will be updated accordingly. Only if it is set, it will pull the other registers.

Best regards, elmerucr

**Comment by ghost** [comment]
Oh yes, reading again, thats right, sorry for the mess!. Thank you for helping me notice! Best regards!
